import Hero from "@/components/Hero";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>VDC Telecom</title>
        <meta name="description" content="Generated by kanjī."></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Hero heading="VDC Telecom" message="Les Solutions Avancées sur IP" /> */}
    </div>
  );
}
